language: sass
node_js:
  - "0.10.31"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install: npm install
before_script:
  - gem install sass
  - bower install
script:
  - grunt test